### PR TITLE
Using on non-windows OS

### PR DESCRIPTION
**Pull request by darrrk**

### CODE REVIEW

**Comment by unknownbrackets** [comment]
With the exception of 7-zip (maybe p7zip would help), nothing in maxcso is tied to Windows.

See here:
https://github.com/unknownbrackets/maxcso#platforms

I'd rather avoid recommending WINE.  I'm much more interested in a native port, which would probably perform better (I'm not sure how well overlapped IO in libuv translates through WINE to async IO.)

-[Unknown]

**Comment by darrrk** [comment]
I find way to use this project on linux and it works.
If you prefer native ports, need to give user turnkey solutions (deb, rpm, pkg, e.t.c...).
At least, create `Makefile` for manual compiling on UNIX.

**Comment by unknownbrackets** [comment]
Thanks - I'm not meaning to dismiss that WINE works or that as a temporary workaround.  It's just that if I saw WINE as the recommended solution in a project, I'd assume it relies on Windows APIs - that's not the case here, everything relies on portable APIs.

I don't want other people who might be interested in porting maxcso to come across this and make the same assumption.

-[Unknown]

**Comment by unknownbrackets** [comment]
@darrrk I created a makefile and some instructions:
https://github.com/unknownbrackets/maxcso/compare/unix

Unfortunately, 7-zip has problems (as expected), and needs more work.  Right now, it hangs.  Without 7-zip support, compression will be slightly worse.

-[Unknown]

**Comment by darrrk** [comment]
Cool! Unix users will be more happy now :)

**Comment by unknownbrackets** [comment]
I've updated the unix branch:

https://github.com/unknownbrackets/maxcso/tree/unix

It now supports 7-zip's deflate algorithm (typically better than zlib's deflate) - stupid mistake, probably from a function I copied over from p7zip.  Works fine now.

Feel free to test and report issues, will release a new version with it merged in a little while.

-[Unknown]

**Comment by unknownbrackets** [comment]
Released as v1.8.0.

-[Unknown]

**Pull request closed without merging**
